name: CI

on:
  push:
    branches:
    - master
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Connect to host via SSH and update containers
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSHKEY }}
          command: |
            cd metawipe
            
            docker kill metawipe_container
            docker container prune

            git pull
            
            docker build -t metawipe . 
            docker run -dp 80:80 --name metawipe_container metawipe 